sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '10'
cache:
- node_modules
before_install:
- export DISPLAY=:99.0
- export NG_CLI_ANALYTICS=ci
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run lint && npm run coverage && ng e2e && cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
